### ISSUE TITLE
Can you share a pretrained model ?

### ISSUE THREAD

**Issue by hoangkhoiLE** [nikitataf/vehicle-recognition#1]
Hello @nikitataf , thank for your excellent work. I want to try your approach but I don't have a gpu to train your type of model. Can you share your model for me , so I can try it ? Thank in advance !

Best regards

**Comment by nikitataf** [comment]
Hi @hoangkhoiLE ! Thank you, it is been a while but I have found **Xception** model and uploaded it as an example.

**Comment by hoangkhoiLE** [comment]
Thank you a lot for your kind !
